[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- server/"

[build.environment]
  VITE_API_URL = "http://68.183.173.197"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200